"""initial

Revision ID: 62732477509a
Revises: 
Create Date: 2026-06-23 16:41:55.396607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62732477509a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_username'), 'owner', ['username'], unique=False)
    op.create_table('media_archive_entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shortcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('typename', sa.Enum('image', 'video', 'sidecar', name='typenameenum'), nullable=False),
    sa.Column('is_video', sa.Boolean(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_archive_entries_owner_id'), 'media_archive_entries', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_archive_entries_shortcode'), 'media_archive_entries', ['shortcode'], unique=True)
    op.create_index(op.f('ix_media_archive_entries_taken_at'), 'media_archive_entries', ['taken_at'], unique=False)
    op.create_table('audio_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('song_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uses_original_audio', sa.Boolean(), nullable=False),
    sa.Column('audio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['media_archive_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_infos_entry_id'), 'audio_infos', ['entry_id'], unique=True)
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_video', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('video_duration', sa.Float(), nullable=True),
    sa.Column('accessibility_caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['media_archive_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'position')
    )
    op.create_index(op.f('ix_media_items_entry_id'), 'media_items', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_items_entry_id'), table_name='media_items')
    op.drop_table('media_items')
    op.drop_index(op.f('ix_audio_infos_entry_id'), table_name='audio_infos')
    op.drop_table('audio_infos')
    op.drop_index(op.f('ix_media_archive_entries_taken_at'), table_name='media_archive_entries')
    op.drop_index(op.f('ix_media_archive_entries_shortcode'), table_name='media_archive_entries')
    op.drop_index(op.f('ix_media_archive_entries_owner_id'), table_name='media_archive_entries')
    op.drop_table('media_archive_entries')
    op.drop_index(op.f('ix_owner_username'), table_name='owner')
    op.drop_table('owner')
    # ### end Alembic commands ###
